@api = http://localhost:4000/

GET {{api}}videos
###
GET {{api}}videos/14
###
POST {{api}}videos
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=ybPmxCKWxko",
    "title": "fazt video mern segunda parte",
    "description": "this is a fazt video"
}
###
PUT {{api}}videos/8
Content-Type: application/json

{
    "title": "stack MERN"
}
###
DELETE {{api}}videos/4